### ISSUE TITLE
Support print statements in generators

### ISSUE THREAD

**Issue by heburson** [StevenClontz/checkit-platform#1]
When creating my first question bank this morning, I kept getting the following error: "JSONDecodeError: Extra data: line 2 column 1 (char 3)." I figured out that it was because I had print statements in my generator function that I had been using for earlier debugging.  It might be worth stating somewhere in the documentation that you cannot have print statements in the generator function. I'm sure I am not the only person who uses them liberally for debugging.

**Comment by StevenClontz** [comment]
Ah, good point! CheckIt works by having SageMath print out the JSON to stdout which is read by a Python program, so any additional printing will mess that up. I'll add that to the docs, but it's worth considering if this data shouldn't be passed along in some other fashion (e.g. writing JSON to disk).

As for development patterns: the "preview exercise" button shows what the generator returns, so I often add an extra `"debug": thing_i_want_to_see` to the returned dictionary.

**Comment by StevenClontz** [comment]
Added documentation in 97e1272

**Comment by StevenClontz** [comment]
Moved issue to dashboard repo
